---
title: "Reanalysis ManyLabs 4"
author: "Julia Haaf"
date: "2/11/2020"
output: pdf_document
---

```{r, message = F}
library(BayesFactor)
library(MCMCpack)
library(knitr)
library(kableExtra)
library(metafor)
library(papaja)
require(ggplot2)

ggplot2::theme_set(theme_apa(base_size = 10))
```

```{r bf-function}
bayesBF <- function(dat, rScale = c(1, .4, .24), M = 30000, Mprior = 200000)
{
	N <- nrow(dat)
	J <- length(unique(dat$source))
	loc <- unique(dat$source)
	cond <- 2 - as.numeric(dat$ms_condition)
	alpha <- 1:J
	beta <- (J + 2):(2 * J + 1)
	mu <- J + 1
	X <- matrix(nrow = N, ncol = 2 * J + 1, 0)
	
	for(i in 1:N){
  locit <- which(loc == dat$source[i])
  X[i, locit] <- 1
  X[i, J + 1] <- cond[i]
  X[i, J + 1 + locit] <- cond[i]
  }
	gMap <- rep(0:2, c(J, 1, J))
	samples <- nWayAOV(dat$pro_minus_anti, X
	                   , gMap, rscale = rScale
	                   , posterior = T, iterations = M)
	bfFull <- nWayAOV(dat$pro_minus_anti, X
	                  , gMap, rscale = rScale
	                  , posterior = F, iterations = M)$bf
	bfNull <- nWayAOV(dat$pro_minus_anti, X[ , 1:J]
	                  , gMap[1:J], rscale = rScale[1]
	                  , posterior = F, iterations = M)$bf
	bfOne <- nWayAOV(dat$pro_minus_anti, X[ , 1:(J + 1)]
	                 , gMap = rep(0:1, c(J, 1),), rscale = rScale[1:2]
	                 , posterior = F, iterations = M)$bf
	samplesOne <- nWayAOV(dat$pro_minus_anti, X[ , 1:(J + 1)]
	                      , gMap = rep(0:1, c(J, 1),), rscale = rScale[1:2]
	                      , posterior = T, iterations = M)
	
	#Positive Effects (random)
	effect <- samples[500:M, beta + 1] + samples[500:M, mu + 1]
	post.pos <- mean(apply(effect > 0, 1, mean) == 1)
	gm <- rinvgamma(Mprior, .5, .5 * rScale[3]^2)
	m.1 <- rnorm(Mprior, 0, sqrt(gm))
	g <- rinvgamma(Mprior, .5, .5*rScale[2]^2)
	a1 <- 1:Mprior
	for (m in 1:Mprior) a1[m] = mean(rnorm(J, m.1[m], sqrt(g[m])) > 0)
	prior.pos <- mean(a1 == 1)
	
	#Positive Effect (common)
	effectOne <- samplesOne[500:M, mu + 1]
	post.pos.One <- mean(effectOne > 0)
	bfpostUpdate <- post.pos.One / .5
	
	bf <- c(exp(bfFull - bfNull)
	        , exp(bfOne - bfNull) * bfpostUpdate
	        , exp(bfFull - bfNull) * post.pos/prior.pos)
	out <- c(bf, post.pos, prior.pos)
	names(out) <- c("F0", "10", "P0", "post.pos", "prior.pos")
	return(list("bfs" = out, "effects" = effect, "N" = nrow(dat)))
}

simple.fig <- function(dat){
  meansbycondloc <- with(dat
                         , tapply(pro_minus_anti
                                  , list(source, ms_condition)
                                  , mean, na.rm = TRUE))
  effects <- meansbycondloc[, 1] - meansbycondloc[, 2]
  plot(sort(effects)
       , pch = 19, ylab = "Effect", xlab = "Source")
  abline(h = 0)
}
```

```{r resFig-fun, echo = F}
resFig <- function(effects, dat, names = FALSE){
  dat$sourcef <- factor(dat$source, levels = unique(dat$source))
  meansbycondloc <- with(dat, tapply(pro_minus_anti, list(sourcef, ms_condition), mean, na.rm = TRUE))
  obs.effects <- meansbycondloc[, 1] - meansbycondloc[, 2]
  order.ef <- rev(order(obs.effects))
  obs.ci <- t(sapply(unique(dat$source)
                          , function(x) t.test(dat$pro_minus_anti[dat$source==x] ~ dat$ms_condition[dat$source==x]
                                               , var.equal = T)$conf.int))
  pm.effects <- colMeans(effects) 
  est.ci <- t(apply(effects, 2, quantile, probs = c(.025, .975)))
  I <- length(obs.effects)
  
  dfBoth <- data.frame(effectSize = c(obs.effects[order.ef], pm.effects[order.ef]),
                     y = c(1:I, (1:I) - .4),
                     studyLabels = c(as.character(unique(dat$source)), rep("", I)),
                     # weight_scaled = c(weight_scaled[order.ef], weight_estimated_scaled[order.ef]), 
                     lower = c(obs.ci[order.ef, 1], est.ci[order.ef, 1]), 
                     upper = c(obs.ci[order.ef, 2], est.ci[order.ef, 2]),
                     g = rep(c("Observed", "Estimated"), each = I))
  dfLab <- data.frame(studyLabels = as.character(unique(dat$source))[order.ef]
                    , y <- 1:I)
    
  plot <-  ggplot2::ggplot(dfBoth, ggplot2::aes(x = effectSize, y = y)) +
           ggplot2::geom_vline(xintercept = 0, linetype = "dotted") +
           ggplot2::geom_point(ggplot2::aes(shape = as.factor(dfBoth$g), colour = as.factor(dfBoth$g))) +
           ggplot2::geom_errorbarh(ggplot2::aes(xmin = dfBoth$lower
                                               , xmax = dfBoth$upper, colour = as.factor(dfBoth$g))
                                  , height = .1, show.legend = FALSE) +
           ggplot2::scale_y_continuous(breaks = dfLab$y, labels = as.character(dfLab$studyLabels)) +
           ggplot2::scale_color_manual("", values = c("black", "slategrey"), labels = c("Estimated", "Observed")) +
           ggplot2::scale_shape_manual("", values = c(16, 15)) +
           ggplot2::guides(shape = ggplot2::guide_legend(reverse=TRUE, override.aes = list(size=3))
                           , colour = ggplot2::guide_legend(reverse=TRUE)) +
           ggplot2::theme(axis.text.y.right = ggplot2::element_text(colour = c(rep(c("slategrey", "black"), each = I)))) +
           ggplot2::xlab("Mortality Salience Effect") +
           ggplot2::ylab(" ")
  plot
}
```

## Reanalysis with Exclusion Criterion .1.1

This is the original main analysis that is the basis for the key claims of the Many Labs 4 project.

```{r}
dat.111 <- read.csv2("data/reanalysis_111.csv", header = T)
dat.211 <- read.csv2("data/reanalysis_211.csv", header = T)
dat.311 <- read.csv2("data/reanalysis_311.csv", header = T)
```

```{r reanalysis-111, cache = T, message=F, warning=F}
rean.111 <- bayesBF(dat = dat.111)
rean.111$bfs
resFig(rean.111$effects, dat = dat.111)
```

```{r reanalysis-211, cache = T, message=F, warning=F}
rean.211 <- bayesBF(dat = dat.211)
rean.211$bfs
resFig(rean.211$effects, dat = dat.211)
```

```{r reanalysis-311, cache = T, message=F, warning=F}
rean.311 <- bayesBF(dat = dat.311)
rean.311$bfs
resFig(rean.311$effects, dat = dat.311)
```

## Reanalysis with Exclusion Criterion .3.2

(1,3,2), (2,3,2), and (3,3,2)

```{r}
dat.132 <- read.csv2("data/reanalysis_132.csv", header = T)
dat.232 <- read.csv2("data/reanalysis_232.csv", header = T)
dat.332 <- read.csv2("data/reanalysis_332.csv", header = T)
```

```{r reanalysis-132, cache = T, message=F, warning=F}
rean.132 <- bayesBF(dat = dat.132)
rean.132$bfs
resFig(rean.132$effects, dat = dat.132)
```

```{r reanalysis-232, cache = T, message=F, warning=F}
rean.232 <- bayesBF(dat = dat.232)
rean.232$bfs
resFig(rean.232$effects, dat = dat.232)
```

```{r reanalysis-332, cache = T, message=F, warning=F}
rean.332 <- bayesBF(dat = dat.332)
rean.332$bfs
resFig(rean.332$effects, dat = dat.332)
```

## Summary

\renewcommand{\arraystretch}{2}

```{r, results="asis"}
BFs <- rbind(rean.111$bfs, rean.211$bfs, rean.311$bfs, rean.132$bfs, rean.232$bfs, rean.332$bfs)
BFs <- round(1/ BFs[, 1:3], 2)
Ns <- c(rean.111$N, rean.211$N, rean.311$N, rean.132$N, rean.232$N, rean.332$N)
BFs <- cbind(Ns, BFs)
rownames(BFs) <- paste("Exclusion Criterion", c(111, 211, 311, 132, 232, 332))
colnames(BFs) <- c("Sample Size", "$BF_{0f}$", "$BF_{01}$", "$BF_{0+}$")

apa_table(BFs, escape = FALSE, caption = "Bayes factors for key analyses.", note = "All Bayes factors are reported in favor of the null model.")
# 
# kable(BFs, escape = FALSE, format = "latex") %>%
#   kable_styling(latex_options = "striped", font_size = 12)
```

