---
title: "Reanalysis"
author: "Julia Haaf"
date: "3/5/2020"
output: pdf_document
---

```{r}
library(ggpubr)
library(metaBMA)
library(ggplot2)
library(knitr)
library(kableExtra)
library(papaja)
library(lemon)

ggplot2::theme_set(theme_apa(base_size = 14))
```

```{r re-fig-all, echo = F}
forest.all <- function(obs.data, es.data, est.averaging, est.multilevel, legend.pos){
# Returns a forest plot with observed and estimated effects
  
  I <- nrow(es.data)
  ord <- order(es.data$yi) #everything is sorted by effect size
  labord <- es.data$source[ord]
  es <- es.data$yi[ord]
  est.es <- est.averaging[ord, "est.es"]
  est.lower.es <- est.averaging[ord, "est.lower"]
  est.upper.es <- est.averaging[ord, "est.upper"]
  studyLabels <- es.data[ord, "labelpretty"]  

  lower.es <- es - qnorm(1 - .05/2) * es.data$sei 
  upper.es <- es + qnorm(1 - .05/2) * es.data$sei

  y.obs.es <- I:1
  y.est.es <- rev(seq(.6, I - .4, 1))

  dfBoth.av <- data.frame(es = c(es, est.es),
                       y = c(y.obs.es, y.est.es),
                       studyLabels = c(studyLabels, studyLabels),
                       lower = c(lower.es, est.lower.es), upper = c(upper.es, est.upper.es),
                       g = rep(c("Observed", "Estimated"), each = I)
                       )
  
  obs.data$sourcef <- factor(obs.data$source, levels = unique(obs.data$source))
  meansbycondloc <- with(obs.data, tapply(pro_minus_anti, list(sourcef, ms_condition), mean, na.rm = TRUE))
  obs.effects <- meansbycondloc[, 1] - meansbycondloc[, 2]
  obs.ci <- t(sapply(unique(obs.data$source)
                          , function(x) t.test(obs.data$pro_minus_anti[obs.data$source==x] ~ obs.data$ms_condition[obs.data$source==x]
                                               , var.equal = T)$conf.int))
  pm.effects <- colMeans(est.multilevel) 
  est.ci <- t(apply(est.multilevel, 2, quantile, probs = c(.025, .975)))
  lab.multiord <- unique(obs.data$source)
  ordmulti <- match(labord, lab.multiord)

  dfBoth.mu <- data.frame(effectSize = c(obs.effects[ordmulti], pm.effects[ordmulti]),
                     y = c(y.obs.es, y.est.es),
                     studyLabels = c(studyLabels, studyLabels),
                     lower = c(obs.ci[ordmulti, 1], est.ci[ordmulti, 1]), 
                     upper = c(obs.ci[ordmulti, 2], est.ci[ordmulti, 2]),
                     g = rep(c("Observed", "Estimated"), each = I))
    
  plot.mu <-  ggplot2::ggplot(dfBoth.mu, ggplot2::aes(x = effectSize, y = y)) +
           ggplot2::geom_vline(xintercept = 0, linetype = "dotted") +
           ggplot2::geom_point(ggplot2::aes(shape = as.factor(dfBoth.mu$g), colour = as.factor(dfBoth.mu$g)), size = 3) +
           ggplot2::geom_errorbarh(ggplot2::aes(xmin = dfBoth.mu$lower
                                               , xmax = dfBoth.mu$upper, colour = as.factor(dfBoth.mu$g))
                                  , height = .3, show.legend = FALSE, size = .8) +
           ggplot2::scale_y_continuous(breaks = I:1, labels = rep(" ", I),
                                    expand = c(0, 0.5)) +
           ggplot2::scale_color_manual("", values = c("black", "slategrey"), labels = c("Estimated", "Observed")) +
           ggplot2::scale_shape_manual("", values = c(16, 15)) +
           ggplot2::guides(shape = ggplot2::guide_legend(reverse=TRUE, override.aes = list(size=3))
                           , colour = ggplot2::guide_legend(reverse=TRUE)) +
           ggplot2::theme(axis.text.y.right = ggplot2::element_text(colour = c(rep(c("slategrey", "black"), each = I)))) +
           ggplot2::xlab("Unstandardized \n Effect") +
           ggplot2::ylab(" ") +
           theme(axis.line.y = element_blank(),
                 axis.ticks.y = element_blank(),
                 legend.margin = margin(t = 0, unit='cm'),
                 legend.position = if(legend.pos == 2){c(0.1, 0.15)}else{"none"})

  plot.av <- ggplot(dfBoth.av, aes(x = es, y = y)) +
        geom_vline(xintercept = 0, linetype = "dotted") +
        geom_point(aes(shape = as.factor(dfBoth.av$g), colour = as.factor(dfBoth.av$g)), size = 3) +
        ggplot2::geom_errorbarh(ggplot2::aes(xmin = dfBoth.av$lower
                                               , xmax = dfBoth.av$upper, colour = as.factor(dfBoth.av$g))
                                  , height = .3, show.legend = FALSE, size = .8) +
        scale_y_continuous(breaks = I:1, labels = as.character(studyLabels),
                                    expand = c(0, 0.5)) +
        scale_color_manual("", values = c("black", "slategrey"), 
                                    labels = c(gettext("Estimated"), gettext("Observed"))) +
        scale_shape_manual("", values = c(16, 15)) +
        guides(shape = guide_legend(reverse=TRUE, override.aes = list(size=3)), 
               colour = guide_legend(reverse=TRUE))  +
        xlab("Standardized \n Effect") +
        ylab(" ") +
        theme(axis.line.y = element_blank(),
              axis.ticks.y = element_blank(),
              legend.position = if(legend.pos == 1){c(0.8, 1)}else{"none"})

  ggarrange(plot.av, plot.mu,
            labels = c("A.", "B."),
            ncol = 2, nrow = 2
            , widths = c(.64, .36))
}
```



This document combines all analyses to draw plots.

## Running Analyses

```{r include-hierarchical, cache = TRUE, child = "reanalysis-multilevel.Rmd"}
```

```{r include-averaging, cache = TRUE, child = "reanalysis-modelaveraging.Rmd"}
```

## Plots Original Analysis

```{r}
m.111$source
m.111$labelpretty <- c("Ashland University", "Azusa Pacific University", "Brigham Young University - Idaho", "The College of New Jersey", "University of Illinois", "Ithaca College", "University of Kansas - Expert", "University of Kansas - In House", "Occidental College", "Pace University - Expert", "Pace University - In House", "Pacific Lutheran University", "University of California, Riverside", "Southern Oregon University", "University of Florida", "University of Pennsylvania", "University of Wisconsin - Expert", "University of Wisconsin - In House", "Virginia Commonwealth University", "Wesleyan University", "Worcester Polytechnic Institute")

m.211$source
m.211$labelpretty <- c("Ashland University", "Azusa Pacific University", "Brigham Young University - Idaho", "The College of New Jersey", "Ithaca College", "University of Kansas - Expert", "Occidental College", "Pace University - Expert", "University of California, Riverside", "University of Pennsylvania", "University of Wisconsin - Expert", "Virginia Commonwealth University")

m.311$source
m.311$labelpretty <- c("Ashland University", "Brigham Young University - Idaho", "The College of New Jersey", "University of Kansas - Expert", "Occidental College", "Pace University - Expert", "University of California, Riverside", "University of Wisconsin - Expert", "Virginia Commonwealth University")

m.332$source
m.332$labelpretty <- c("Brigham Young University - Idaho", "The College of New Jersey", "Occidental College", "Pace University - Expert", "University of California, Riverside", "University of Wisconsin - Expert", "Virginia Commonwealth University")
```


```{r forests-111, fig.width=10, fig.height=14}
forest.all(obs.data = dat.111, es.data = m.111, est.averaging = rema.111$est$default, est.multilevel = rean.111$effects, legend.pos = 2)
```

```{r forests-211, fig.width=10, fig.height=10}
forest.all(obs.data = dat.211, es.data = m.211, est.averaging = rema.211$est$default, est.multilevel = rean.211$effects, legend.pos = 2)
```

```{r forests-311, fig.width=10, fig.height=9}
forest.all(obs.data = dat.311, es.data = m.311, est.averaging = rema.311$est$default, est.multilevel = rean.311$effects, legend.pos = 2)
```

```{r forests-332, fig.width=10, fig.height=9}
forest.all(obs.data = dat.332, es.data = m.332, est.averaging = rema.332$est$default, est.multilevel = rean.332$effects, legend.pos = 1)
```


## Combining Evidence from multiverse analysis

```{r cache = T, message=F, warning=F}
sets <- c(111, 211, 311, 132, 232, 332, 112, 212, 312, 121, 221, 321, 122, 222, 322, 131, 231, 331)
ssize <- data.frame("metaset" = character(),
                    "N" = numeric(),
                    "N.study" = numeric()
                         )
for(i in sets){
  path.m <- paste0("data/reanalysis_", i, ".csv")
  m <- read.csv2(path.m, header = T)
  N <- nrow(m)
  path.m <- paste0("data/metaset_", i, ".csv")
  m <- read.csv2(path.m, header = T)
  N.study <- nrow(m)
  ssize <- rbind(ssize, c(i, N, N.study))
}
```


```{r fig-all}
rema.all <- rbind(BFs.og[, 1:3]
                  , BFs.cmnt[, 1:3]
                  , rema.other
                  )
rema.all <- 1/rema.all
rema.all <- cbind(rema.all, "N" = ssize[, 2], "N.study" = ssize[, 3])
rema.all <- cbind(rema.all, "Crit" = rownames(rema.all))
result <- tidyr::gather(rema.all, prior, bf, Default:Vohs, factor_key = TRUE)
result$Nscaled <- result$N.study/2

result <- result[!duplicated(result$bf),]

xrange <- c(0, 2500)
yrange <- c(1/50, 50) # log scale

# Plot with n participants included on the x-axis, BF01 on the y-axis, colors for
# participant exclusion sets and bubble sizes for number of studies included
ggplot(aes(x = N, y = bf, size = Nscaled, color = as.factor(prior)), data = result) +
  geom_point(alpha = 0.6) +
  scale_y_continuous(trans='log', limits = yrange, breaks = c(1/50, 1/5, 1, 5, 50)) +
  scale_size_identity() +
  scale_colour_brewer(palette = 'Dark2') +
  labs(x = 'Sample Size', y = expression(BF["10"]), color = "Priors") +
  xlim(xrange) +
  geom_hline(yintercept = 1) + 
  theme_apa() +
  theme_classic(base_size = 19) +
  theme(axis.line=element_line()) +
  guides(color = guide_legend(override.aes = list(size = 4))) +
  coord_capped_cart(gap = 0.1, bottom = 'none', left = 'none') + #caps the axes so they don't touch
  theme(axis.title.x = element_text(vjust=-0.5),
        axis.text.x = element_text(vjust=-0.5),
        axis.text.y = element_text(hjust=.8,),
        axis.ticks.length = unit(0.25, 'cm'),
        legend.position = c(0.8, .85)
        )
```

```{r}
crits <- data.frame(matrix(unlist(strsplit(as.character(sets), split = c())), ncol = 3, byrow = T))
colnames(crits) <- c("Participant-level", "N-based", "Protocol")
crits$`Participant-level` <- ifelse(crits$`Participant-level` == 1, "All"
                                    , ifelse(crits$`Participant-level` == 2, "White & US-born", "US-Identity > 7"))
crits$`N-based` <- ifelse(crits$`N-based` == 1, "All"
                                    , ifelse(crits$`N-based` == 2, "N > 60", "N > 80"))
crits$Protocol <- ifelse(crits$Protocol == 1, "All", "AA")

tab.all <- cbind(crits, rema.all[, c("N", "N.study")])
tab.all <- tab.all[order(tab.all$`N-based`), ]        
tab.all <- tab.all[c(1:12, 16:18, 13:15),]

apa_table(tab.all
          , note = "Bla"
          , caption = "Exclusion constellations and resulting sample sizes"
          , col.names = c("Participant-level", "N-based", "Protocol", "Sample Size", "Number of Studies")
          , row.names = F
          , digits = 0)
```


## Additional Info

Overall effect size estimates

```{r, cache = T}
default.prior.unconstrained     <- prior(family = "t",
                                         param = c(0, 0.707, 1)
                                         )
priors.es <- list(default = default.prior.unconstrained
               )

rema.111.es <- .runRema(m.111$yi, m.111$sei, priors.es, TRUE)
rema.211.es <- .runRema(m.211$yi, m.211$sei, priors.es, TRUE)
rema.311.es <- .runRema(m.311$yi, m.311$sei, priors.es, TRUE)
```

```{r, cache = T}
rema.132.es <- .runRema(m.132$yi, m.132$sei, priors.es, TRUE)
rema.232.es <- .runRema(m.232$yi, m.232$sei, priors.es, TRUE)
rema.332.es <- .runRema(m.332$yi, m.332$sei, priors.es, TRUE)
```



```{r, results="asis"}
es.tab <- rbind(
  rema.111.es$m.est[[1]]
  , rema.211.es$m.est[[1]]
  , rema.311.es$m.est[[1]]
  , rema.132.es$m.est[[1]]
  , rema.232.es$m.est[[1]]
  , rema.332.es$m.est[[1]]
)

kable(round(es.tab, 2), col.names = c("ES", "2.5%", "95%"))
```


```{r forests-111-unconstrained, fig.width=10, fig.height=14}
forest.all(obs.data = dat.111, es.data = m.111, est.averaging = rema.111.es$est$default, est.multilevel = rean.111$effects, legend.pos = 2)
```

```{r forests-211-unconstrained, fig.width=10, fig.height=10}
forest.all(obs.data = dat.211, es.data = m.211, est.averaging = rema.211.es$est$default, est.multilevel = rean.211$effects, legend.pos = 2)
```

```{r forests-311-unconstrained, fig.width=10, fig.height=9}
forest.all(obs.data = dat.311, es.data = m.311, est.averaging = rema.311.es$est$default, est.multilevel = rean.311$effects, legend.pos = 2)
```

```{r forests-332-unconstrained, fig.width=10, fig.height=9}
forest.all(obs.data = dat.332, es.data = m.332, est.averaging = rema.332.es$est$default, est.multilevel = rean.332$effects, legend.pos = 1)
```
